In [6]:
import numpy as np

# Example dimensions
num_runs = 2
freq_points = 4
sweeps_per_run = 2
n_bins = 2

# Example data
arr = np.random.rand(num_runs, freq_points * sweeps_per_run, n_bins)
print('Init array:')
print(arr)

# Reshape to expose freq_points dimension
arr_reshaped = arr.reshape(num_runs,sweeps_per_run , freq_points, n_bins)
print('Reshaped array:')
print(arr_reshaped)

# Sum over all but freq_points
result = arr_reshaped.sum(axis=(0, 2, 3))
print('Result array:')
print(result)

# print(result.shape)  # (10,)

(4, 3)


In [15]:
import numpy as np

# Example dimensions
num_runs = 2
freq_points = 4
sweeps_per_run = 2
n_bins = 3

# Example data
arr = np.random.rand(num_runs, freq_points * sweeps_per_run, n_bins)
print('Init array:')
print(arr)

# Step 1: reshape to separate freq_points and sweeps_per_run
arr_reshaped = arr.reshape(num_runs*sweeps_per_run,freq_points, n_bins)
print('Reshaped array:')
print(arr_reshaped)

# Step 2: sum over runs and sweeps
result = arr_reshaped[0:2,:,:].sum(axis=(0))
print('Result array:')
print(result)

# print(result.shape)  # (freq_points, n_bins)

Init array:
[[[0.62892603 0.36942199 0.23911342]
  [0.24817617 0.5147836  0.46412376]
  [0.62516146 0.39593354 0.72269709]
  [0.51111603 0.20678146 0.95649543]
  [0.70496987 0.52290801 0.83956373]
  [0.60784447 0.33065474 0.42313579]
  [0.31772328 0.91764137 0.55923245]
  [0.85236422 0.5706384  0.74823005]]

 [[0.87146684 0.57634928 0.98659538]
  [0.76648181 0.46111978 0.192022  ]
  [0.61811464 0.69498265 0.67696261]
  [0.10295929 0.26311319 0.63594963]
  [0.99903762 0.36286157 0.90817301]
  [0.62400499 0.58314736 0.98973274]
  [0.80802449 0.59520458 0.12597958]
  [0.8545782  0.24285477 0.31254822]]]
Reshaped array:
[[[0.62892603 0.36942199 0.23911342]
  [0.24817617 0.5147836  0.46412376]
  [0.62516146 0.39593354 0.72269709]
  [0.51111603 0.20678146 0.95649543]]

 [[0.70496987 0.52290801 0.83956373]
  [0.60784447 0.33065474 0.42313579]
  [0.31772328 0.91764137 0.55923245]
  [0.85236422 0.5706384  0.74823005]]

 [[0.87146684 0.57634928 0.98659538]
  [0.76648181 0.46111978 0.192022  ]
  